In [4]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv('Desktop\smsspamcollection\SMSSpam.tsv',sep='\t',names=['Status','Messages'])

In [6]:
df.head()

Status                                           Messages
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
df.loc[df['Status']=='ham','Status']=1
df.loc[df['Status']=='spam','Status']=0

In [8]:
df.head()

Status                                           Messages
0      1  Go until jurong point, crazy.. Available only ...
1      1                      Ok lar... Joking wif u oni...
2      0  Free entry in 2 a wkly comp to win FA Cup fina...
3      1  U dun say so early hor... U c already then say...
4      1  Nah I don't think he goes to usf, he lives aro...

In [9]:
df_x=df["Messages"]
df_y=df["Status"]

In [15]:
from sklearn.feature_extraction.text import  TfidfVectorizer
cv1=TfidfVectorizer(min_df=1,stop_words='english')

In [16]:
from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df_x,df_y,test_size=0.2,random_state=4)

In [17]:
x_traincv=cv1.fit_transform(x_train)
a=x_traincv.toarray()
a

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.19618715, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [18]:
cv1.inverse_transform(a[0])

[array(['checking', 'going', 'got', 'haha', 'lor', 'mails', 'online',
        'replying', 'sleeping', 'spys', 'wat'], dtype='<U27')]

In [19]:
x_train.iloc[0]

'U sleeping now.. Or you going to take? Haha.. I got spys wat.. Me online checking n replying mails lor..'

In [20]:
from sklearn.naive_bayes import MultinomialNB

In [21]:
mnb=MultinomialNB()

In [24]:
y_train=y_train.astype(int)

In [25]:
mnb.fit(x_traincv,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [26]:
x_testcv=cv1.transform(x_test)

In [27]:
pred=mnb.predict(x_testcv)

In [28]:
pred


array([1, 1, 1, ..., 1, 1, 0])

In [29]:
actual=np.array(y_test)

In [30]:
actual

array([1, 1, 1, ..., 1, 1, 0], dtype=object)

In [32]:
count=0

In [33]:
for i in range(len(pred)):
    if pred[i]==actual[i]:
     count=count+1

In [34]:
count

1068

In [35]:
len(pred)

1115

In [36]:
1068/1115


0.957847533632287